name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_client_id: ${{ secrets.FITBIT_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.FITBIT_CLIENT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.4
      
      # - name: Create terraform.tfvars file
      #   run: |
      #     cd terraform
      #     echo 'fitbit_client_id = "${{ secrets.FITBIT_CLIENT_ID }}"' >> terraform.tfvars
      #     echo 'fitbit_client_secret = "${{ secrets.FITBIT_CLIENT_SECRET }}"' >> terraform.tfvars
      #     cat terraform.tfvars

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Execute Terraform
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve